name: Test GitHub Pages Deployment

on:
  push:
    branches:
      - test-deploy  # Change this to the branch you want to test

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install Jekyll dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Test deployment (dry run)
        run: |
          echo "Build successful!"
          echo "Site preview available at _site/index.html"
